---
title: "COVID-19 pandemic from metabolomic perspective"
site: distill::distill_website
bibliography: novia_ref.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```

As of 7th April 2021, the COVID-19 pandemic, caused by severe acute respiratory syndrome coronavirus 2 (SARS-Cov-2), has spread to 223 countries, infected > 133.5 million people and killed > 2.8 million people [@whocovid19]. 

Similar to other viral infections, every individual responses differently to the virus. Most individuals experience mild sore throat, fever and fatigue. Some are even asymptomatic. However, a subset of individuals experience severe respiratory distress, organ failure and cytokine storm that results in death [@ayres2020metabolic; @kimhofer2020integrative].

Multiple metabolomics studies have been conducted in an attempt to unravel COVID-19. They found that several amino acids were found to be positively correlated with COVID-19 [@pang2021comprehensive; @delafiori2021covid; @cai2020kynurenic; @blasco2020specific; @thomas2020covid; @kimhofer2020integrative]. 

Several common metabolic pathways, such as porphyrin, cellular amino acidarachidonic acid metabolism were found to be significantly perturbed in COVID-19 patients [@@pang2021comprehensive]. Propanoate metabolism, was identified by Pang et al (2021) as a novel pathway in the progression of COVID-19. Other metabolic pathways such as TCA, selenocompound, mannose and glutathione metabolism were found to be associated with the progression and severity of COVID-19 [@pang2021comprehensive; @polonikov2020endogenous; @li2020insight]

Simply put, each individual's immune system is unique, it relies on multiple metabolic pathways, such as amino acid, energy and lipid metabolism, to initiate and regulate response to COVID-19. Thus it is extremely important to take these individual level's information and pathways information or knowledge into account when conducting a statistical analysis. 
